# ???????????????????????????????????????????
news:
  aggregation:
    mysql:
      url: jdbc:mysql://192.168.1.7:3306/news-aggregation # nft.turbo.mysql.url - MySQL ???+????? #??????????????
      username: root # nft.turbo.mysql.username - MySQL ???? #??????????????
      password: 'wangchuan' # nft.turbo.mysql.password - MySQL ??? #??????????????
    redis:
      url: 192.168.1.7  # nft.turbo.redis.url - Redis ??? #??????????????
      port: 6379  # nft.turbo.redis.port - Redis ???? #??????????????
#      password: 'NFTurbo666' # nft.turbo.redis.password - Redis ??? #??????????????
