spring:
  application:
    name: news-aggregation-news


#Rss??
news:
  rss:
    sources:
      - name: BCC
        url: https://feeds.bbci.co.uk/news/business/rss.xml
        category: Business

      - name: BBC
        url: https://www.bbc.com/culture/feed.rss
        category: Culture

      - name: BBC
        url: https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml
        category: Entertainment


storage:
  minio:
    endpoint: http://192.168.1.10:9001
    access-key: admin
    secret-key: 12345678
    bucket: news-image
    connect-timeout: 10000
    read-timeout: 30000

translate:
  baidu:
    app-id: 20230107001522986
    secret-key: fYkUpOMbbT6m8_YOLJLy
    api-url: https://fanyi-api.baidu.com/api/trans/vip/translate